/*
 * File: app/store/RecentBookData.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eBook.store.RecentBookData', {
    extend: 'Ext.data.Store',

    requires: [
        'eBook.model.ShowBookData'
    ],

    config: {
        data: [
            {
                page: 'resources/images/images.jpg'
            },
            {
                page: 'resources/images/RH_MarkFinancial_FrontPage.jpg'
            },
            {
                page: 'resources/images/shadow.jpg'
            },
            {
                page: 'resources/images/spanish.jpg'
            },
            {
                page: 'resources/images/images.jpg'
            },
            {
                page: 'resources/images/RH_MarkFinancial_FrontPage.jpg'
            },
            {
                page: 'resources/images/images.jpg'
            },
            {
                page: 'resources/images/RH_MarkFinancial_FrontPage.jpg'
            },
            {
                page: 'resources/images/shadow.jpg'
            },
            {
                page: 'resources/images/spanish.jpg'
            },
            {
                page: 'resources/images/images.jpg'
            },
            {
                page: 'resources/images/RH_MarkFinancial_FrontPage.jpg'
            },
            {
                page: 'resources/images/images.jpg'
            },
            {
                page: 'resources/images/RH_MarkFinancial_FrontPage.jpg'
            },
            {
                page: 'resources/images/shadow.jpg'
            },
            {
                page: 'resources/images/spanish.jpg'
            },
            {
                page: 'resources/images/images.jpg'
            },
            {
                page: 'resources/images/RH_MarkFinancial_FrontPage.jpg'
            }
        ],
        model: 'eBook.model.ShowBookData',
        storeId: 'RecentBookData'
    }
});