/*
 * File: app/view/SearchMenu.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eBook.view.SearchMenu', {
    extend: 'Ext.Menu',
    alias: 'widget.searchMenu',

    requires: [
        'Ext.Label'
    ],

    config: {
        style: ' background: #fff;margin-top: 46px;',
        width: 250,
        layout: {
            type: 'vbox',
            align: 'center'
        },
        items: [
            {
                xtype: 'label',
                html: '<div>Search Work under process</div>'
            }
        ]
    }

});