/*
 * File: app/view/Showbook.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eBook.view.ShowBook', {
    extend: 'Ext.Panel',
    alias: 'widget.showbook',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'vbox',
        scrollable: true,
        items: [/*{
		       xtype:'carousel',
			   style:"margin-top:55px;'width:100%;height:60px;",
			   items: [
						{
							html : 'Item 1',
							style: 'background-color: #5E99CC'
						},
						{
							html : 'Item 2',
							style: 'background-color: #759E60'
						},
						{
							html : 'Item 3'
						}
					]
		},*/
           {
                xtype: 'dataview',
                flex: 1,
                id: 'booklist',
                width: '100%',
                inline: {
                    wrap: true
                },
                itemTpl: [
                    '<div style="border:1px solid #ccc;margin: 0px 10px;height: 85px;width:300px;">',
                    '  <table width="100%">',
                    '    <tr>',
                    '        <td rowspan="2" style="font-size: 15px;padding: 5px 0 5px 10px;"><img src={page} style="width: 50px;height: 70px;" /></td>',
                    '        <td style="padding:10px;">',
                    '            <div>Title: {name}</div>',
                    '            <div>Author: {writer}</div>',
                    '            <div>Release Date: {date}</div>',
                    '        </td>',
                    '    </tr>',
                    '</table>',
                    '</div>',
                    '',
                    '',
                    ''
                ],
                store: 'ShowBookData'
            }
        ]
    }

});