/*
 * File: app/view/Showbook.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eBook.view.ShowBook', {
    extend: 'Ext.Panel',
    alias: 'widget.showbook',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
         style: 'margin-top: 55px;',
        layout: 'vbox',
        scrollable:{
            direction:'vartical',
            directionLock:true
        } ,
        items: [{
                xtype: 'panel',
                height: 180,
                style: 'border:1px solid #ccc;margin:0 auto;',
                width: '98%',
                layout: 'hbox',
                scrollable: {
                    direction: 'horizontal',
                    directionLock: true
                },
                items: [
                    {
                        xtype: 'dataview',
                        height:150,
                        flex:1,
                        scrollable: false,
                        id: 'recentBookDataView',
                        width: '100%',
                        inline: {
                            wrap: false
                        },
                        itemTpl: [
                            '<div><img  style="height: 150px;width: 100px; margin: 5px;" src={page} alt=""  /></div>'
                        ],
                        store: 'RecentBookData'
                    }
                ]
            }, {
                xtype: 'panel',
                height: 80,
                margin: '10 0 0 10',
                style: 'border: 1px groove #EFEFEF;background-color: #EFEFEF;margin:0 auto;',
                width: '98%',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'label',
                        html: 'Filter books by',
                        margin: '15 0 15 4',
                        width: '23%'
                    },
                    {
                        xtype: 'textfield',
                        margin: '15 5 15 0',
                        style: 'border: 1px groove #EFEFEF;',
                        width: '23%',
                        placeHolder: 'Category '
                    },
                    {
                        xtype: 'textfield',
                        margin: '15 5 15 0',
                        style: 'border: 1px groove #EFEFEF;',
                        width: '23%',
                        placeHolder: 'Authore'
                    },
                    {
                        xtype: 'textfield',
                        margin: '15 0 15 0',
                        style: 'border: 1px groove #EFEFEF;',
                        width: '23%',
                        placeHolder: 'Name'
                    }
                ]
            },{
                xtype: 'dataview',
                flex: 1,
                id: 'booklist',
                width: '100%',
                inline: {
                    wrap: true
                },
                 style: 'margin-top:10px;',
                itemTpl: [
                    '<div style="border:1px solid #ccc;margin: 0px 10px;height: 85px;width:300px;">',
                    '  <table width="100%">',
                    '    <tr>',
                    '        <td rowspan="2" style="font-size: 15px;padding: 5px 0 5px 10px;"><img src={page} style="width: 50px;height: 70px;" /></td>',
                    '        <td style="padding:10px;">',
                    '            <div>Title: {name}</div>',
                    '            <div>Author: {writer}</div>',
                    '            <div>Release Date: {date}</div>',
                    '        </td>',
                    '    </tr>',
                    '</table>',
                    '</div>',
                    '',
                    '',
                    ''
                ],
                store: 'ShowBookData'
            }
        ]
    }

});